FROM ruby:3.3.5

# Node.js や yarn が必要なら追加（Rails 7 なら通常必要）
RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev nodejs yarn sqlite3

# 作業ディレクトリを作成
WORKDIR /rails

# Gemfile 関連だけ先にコピーして bundle install
COPY Gemfile Gemfile.lock ./
RUN bundle install

# 以降のコードは volume でマウントするので COPY 不要

# 開発環境変数
ENV RAILS_ENV=development

# 起動コマンド
CMD ["bin/rails", "server", "-b", "0.0.0.0"]